# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG Project Name
tagline:          ''
description:      'Project Description'
url:              "https://uwescience.github.io"
baseurl:          "/dssg-website-template"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/dssg-website-template/
