# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG Project Name
tagline:          ''
description:      'Project Description'
url:              "https://uwescience.github.io"
baseurl:          "/DSSG-website-template"


paginate:         5



github:
  repo:           https://github.com/uwescience/DSSG-website-template/
